stages:
  - build
  - test
  - deploy

include:
  - '/app/.gitlab-ci.yml'
  - '/api/.gitlab-ci.yml'

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  script:
    - mv app/build public
    - mv api/bin public/bin
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - master
  needs:
    - job: build-api
      artifacts: true
    - job: build-app
      artifacts: true
    - test-api
    - test-app
