# Extract model from documentation
# Regex: /(.*)\].([a-zA-Z0-9]*).*X([ 	]*)(.*)/
# Replace: "$4"\n$2: String

type Memory {
  total: Float
  free: Float
  used: Float
  active: Float
  available: Float
  buffcache: Float
  swaptotal: Float
  swapused: Float
  swapfree: Float
}

type FileSystem {
  fs: String
  type: String
  size: Float
  used: Float
  use: Float
  mount: String
}

type System {
  platform: String
  distro: String
  release: String
  codename: String
  kernel: String
  arch: String
  hostname: String
}

type CPU {
  manufacturer: String
  brand: String
  speed: String
  cores: Float
}

type Time {
  current: Float
  uptime: Float
  timezone: String
  timezoneName: String
}


type NetworkStats {
  "interface"
  iface: String
  "up / down"
  operstate: String
  "received bytes overall"
  rx_bytes: Float
  "received dropped overall"
  rx_dropped: Float
  "received errors overall"
  rx_errors: Float
  "transferred bytes overall"
  tx_bytes: Float
  "transferred dropped overall"
  tx_dropped: Float
  "transferred errors overall"
  tx_errors: Float
  """
  received bytes / second

  In networkStats() the results / sec. values (rx_sec, tx_sec, ...) are calculated correctly beginning with the second call of the function. It is determined by calculating the difference of transferred bytes / IOs divided by the time between two calls of the function.

  The first time you are calling one of this functions, you will get -1 for transfer rates. The second time, you should then get statistics based on the time between the two calls ...
  """
  rx_sec: Float
  """
  transferred bytes per second

  In networkStats() the results / sec. values (rx_sec, tx_sec, ...) are calculated correctly beginning with the second call of the function. It is determined by calculating the difference of transferred bytes / IOs divided by the time between two calls of the function.

  The first time you are calling one of this functions, you will get -1 for transfer rates. The second time, you should then get statistics based on the time between the two calls ...
  """
  tx_sec: Float
  "interval length (for per second values)"
  ms: Float
}

type Network {
  "interface"
  iface: String
  "interface name"
  ifaceName: String
  "ip4 address"
  ip4: String
  "ip6 address"
  ip6: String
  "MAC address"
  mac: String
  "true if internal interface"
  internal: Boolean
  "true if virtual interface"
  virtual: Boolean
  "up / down"
  operstate: String
  "wireless / wired"
  type: String
  "duplex (full/half)"
  duplex: String
  "MUT maximum transmission unit"
  mtu: Float
  "Speed in Mbit / s"
  speed: Float
  "# changes up/down"
  carrierChanges: Float
  "Current network stats of given interface"
  networkStats: NetworkStats
}

type SystemInformation {
  memory: Memory
  fs: [FileSystem]
  system: System
  cpu: CPU
  time: Time
  "array of network interfaces"
  network: [Network]
  loadAverage: [Float]
}
