variables:
  REACT_APP_FAKE_API: 'true'

test-app:
  image: node:alpine
  stage: test
  script:
    - cd app
    - yarn
    - yarn test-coverage
  cache:
    paths:
    - app/node_modules

lint-app:
  image: node:alpine
  stage: test
  allow_failure: true
  script:
    - cd app
    - yarn
    - yarn lint
  cache:
    paths:
    - app/node_modules

build-app:
  image: node:alpine
  stage: build
  script:
    - cd app
    - yarn
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - app/build
  cache:
    paths:
    - app/node_modules

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  dependencies: ["build-app"]
  script:
    - mv app/build public
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - graphql
