image: node:14.20.1

test-app:
  stage: test
  script:
    - cd app
    - yarn
    - yarn test-coverage
  cache:
    paths:
    - app/node_modules
  needs:
    - build-app

lint-app:
  stage: test
  allow_failure: true
  script:
    - cd app
    - yarn
    - yarn lint
  cache:
    paths:
    - app/node_modules
  needs:
    - build-app

build-app:
  stage: build
  script:
    - cd app
    - yarn
    - yarn build
    - cd build
    - tar -czvf ../public/server-status-app.tar.gz *
    - cd ..
    - REACT_APP_FAKE_API=true yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - app/build
  cache:
    paths:
    - app/node_modules
