stages:
- build
- test

test-api:
  image: node:alpine
  stage: test
  script:
    - yarn
    - yarn test --coverage
  cache:
    paths:
    - node_modules

lint-api:
  image: node:alpine
  stage: test
  allow_failure: true
  script:
    - yarn
    - yarn lint
  cache:
    paths:
    - node_modules

build-api:
  image: node:alpine
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  cache:
    paths:
    - node_modules
