test-api:
  image: node:alpine
  stage: test
  script:
    - cd api
    - yarn
    - yarn test --coverage
  cache:
    paths:
    - api/node_modules
  needs:
    - build-api

lint-api:
  image: node:alpine
  stage: test
  allow_failure: true
  script:
    - cd api
    - yarn
    - yarn lint
  cache:
    paths:
    - api/node_modules
  needs:
    - build-api

build-api:
  image: node:alpine
  stage: build
  script:
    - cd api
    - yarn
    - yarn pkg
  artifacts:
    expire_in: 1 week
    paths:
      - api/dist
      - api/bin
  cache:
    paths:
    - api/node_modules
